#For local development
#bundle exec jekyll serve --config _config.yml,_config_dev.yml
#or
#bundle exec jekyll serve --config _config.yml,_config_dev.yml --watch

url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
